---
title: "vis"
author: "Paulina Han"
date: "2021/10/5"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
library(hexbin)
```

load the data I use very often

```{r}
#load the data I use very often
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USC00519397", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2017-01-01",
    date_max = "2017-12-31") %>%
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Waikiki_HA",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) %>%
  select(name, id, everything())

```


scatter plot

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()

```

fancy

```{r}
#each place each line
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) + #透明
  geom_smooth( se = FALSE) # for each color

#only 1 line 
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .3) + # color for geometry
  geom_smooth( se = FALSE) 


```

```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```

Let's make one more sactter plot
```{r}
weather_df %>% 
  ggplot(aes(x = date, y = tmax, size = prcp)) +
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) + #confidence band "se =FALSE" turn it off
  facet_grid(. ~ name)

```

##use data manipulation as part of this

```{r}
weather_df %>% 
  filter(name == "CentralPark_NY") %>% 
  mutate(
    tmax = tmax * (9/5) + 32,
    tmin = tmin * (9/5) + 32
  ) %>% 
  ggplot(aes(x = tmin, y = tmax)) +
  geom_point()

```

## stacking plot

```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_smooth() 

```

## using hexbin package
```{r}
ggplot(weather_df, aes(x = tmax, y = tmin)) + 
  geom_hex()
```

## univariate plots

```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_histogram() +
  facet_grid(.~name)
```

Lets try some other plots
```{r}
weather_df %>% 
  ggplot(aes(x = tmax, fill = name)) +
  geom_density(alpha = .3)

```

Still with `tmax  and `time`
```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_boxplot()

```
Some people like violin plots

```{r}
weather_df %>% 
  ggplot(aes(x = name, y = tmax)) +
  geom_violin()

```

make ridge plots

```{r}
#need to install ggridges package
weather_df %>% 
  ggplot(aes(x = tmax, y = name)) +
  goem_density_ridges()
```


